### ISSUE TITLE
ui changes

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/gen3.org#6]
- all the buttons are slightly not vertically aligned, is this the problem with the font? 
![image](https://user-images.githubusercontent.com/3324084/47247825-89e35900-d3cb-11e8-9c6f-38764a304def.png)

- “From the perspective of setting up a basic Gen3 ecosystem with all the services running, it was a breeze and the Github docs are pretty awesome.” - can we make this section vertically aligned?
- 
![image](https://user-images.githubusercontent.com/3324084/47248024-265a2b00-d3cd-11e8-973f-5a18f29807cc.png)

why is this section using dark lines to separate instead of alternating colors as other sections?

**Comment by qingyashu** [comment]
> why is this section using dark lines to separate instead of alternating colors as other sections?
Haha It was designed like this 😛
